<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGulEvSl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGulEvSl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGulEvSl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGulEvSl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGulEvSl\App_KernelDevDebugContainer([
    'container.build_hash' => 'GulEvSl',
    'container.build_id' => '532022b2',
    'container.build_time' => 1706646288,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGulEvSl');
