<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ1e5cAF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ1e5cAF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ1e5cAF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ1e5cAF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ1e5cAF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z1e5cAF',
    'container.build_id' => 'a5f168bd',
    'container.build_time' => 1705911721,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ1e5cAF');
